services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - devnet
        depends_on:
            - redis
            - meilisearch
            - mailpit
            - selenium
            - mysql
    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    selenium:
        image: selenium/standalone-chromium
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
          - 'sail-mysql:/var/lib/mysql'
        networks:
          - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
    traefik:
        image: traefik:v3.0
        container_name: netpilot-traefik
        command:
            - '--api.dashboard=true'
            - '--api.insecure=true'
            - '--providers.file.directory=/etc/traefik/dynamic'
            - '--providers.file.watch=true'
            - '--entrypoints.web.address=:80'
            - '--entrypoints.websecure.address=:443'
            - '--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL:-admin@example.com}'
            - '--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json'
            - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web'
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        volumes:
            - './traefik/dynamic:/etc/traefik/dynamic'
            - './traefik/acme.json:/etc/traefik/acme.json'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        networks:
            - sail
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.traefik.rule=Host(`traefik.localhost`)'
            - 'traefik.http.routers.traefik.entrypoints=web'
            - 'traefik.http.services.traefik.loadbalancer.server.port=8080'

networks:
    sail:
        driver: bridge
    devnet:
        external: true

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
    sail-traefik:
        driver: local
    sailredis:
        driver: local
