
  http: 
    routers: 
      netpilot-meadadigital-com: 
        rule: Host(`netpilot.meadadigital.com`)
        service: netpilot-meadadigital-com-service
        middlewares: []
        tls: 
          certResolver: letsencrypt
        
      meadadigital-com: 
        rule: Host(`meadadigital.com`)
        service: meadadigital-com-service
        middlewares: []
        tls: 
          certResolver: letsencrypt
        
      
    
    services: 
      netpilot-meadadigital-com-service: 
        loadBalancer: 
          servers: [
            
              url: http://backend:3001
            
          ]
        
      meadadigital-com-service: 
        loadBalancer: 
          servers: [
            
              url: http://frontend:3000
            
          ]
        
      
    
    middlewares: {}
        
      
    
  
