
  http: 
    routers: 
      netpilot-meadadigital-com-api: 
        rule: Host(`netpilot.meadadigital.com`) && PathPrefix(`/api`)
        service: netpilot-meadadigital-com-api-service
        middlewares: []
        priority: 10
        entryPoints: [
          websecure
        ]
        tls: 
          certResolver: letsencrypt
        
      
      netpilot-meadadigital-com: 
        rule: Host(`netpilot.meadadigital.com`)
        service: netpilot-meadadigital-com-service
        middlewares: []
        priority: 1
        entryPoints: [
          websecure
        ]
        tls: 
          certResolver: letsencrypt
        
      
      netpilot-meadadigital-com-redirect: 
        rule: Host(`netpilot.meadadigital.com`)
        middlewares: [
          netpilot-meadadigital-com-redirect-https
        ]
        entryPoints: [
          web
        ]
      
      api-netpilot-com-redirect: 
        rule: Host(`api.netpilot.com`)
        middlewares: [
          api-netpilot-com-redirect-https
        ]
        entryPoints: [
          web
        ]
      
    
    services: 
      netpilot-meadadigital-com-api-service: 
        loadBalancer: 
          servers: [
            
              url: http://backend:3001
            
          ]
        
      
      netpilot-meadadigital-com-service: 
        loadBalancer: 
          servers: [
            
              url: http://frontend:3000
            
          ]
        
      
    
    middlewares: 
      netpilot-meadadigital-com-redirect-https: 
        redirectScheme: 
          scheme: https
          permanent: true
        
      
      api-netpilot-com-redirect-https: 
        redirectScheme: 
          scheme: https
          permanent: true
        
      
    
  
