
  http: 
    routers: 
      netpilot-meadadigital-com-websocket: 
        rule: Host(`netpilot.meadadigital.com`) && PathPrefix(`/socket.io`)
        service: netpilot-meadadigital-com-api-service
        middlewares: [websocket-headers]
        priority: 15
        entryPoints: [
          websecure
        ]
        tls: 
          certResolver: letsencrypt
        
      netpilot-meadadigital-com-api: 
        rule: Host(`netpilot.meadadigital.com`) && PathPrefix(`/api`)
        service: netpilot-meadadigital-com-api-service
        middlewares: []
        priority: 10
        entryPoints: [
          websecure
        ]
        tls: 
          certResolver: letsencrypt
        
      
      netpilot-meadadigital-com: 
        rule: Host(`netpilot.meadadigital.com`)
        service: netpilot-meadadigital-com-service
        middlewares: []
        priority: 1
        entryPoints: [
          websecure
        ]
        tls: 
          certResolver: letsencrypt
        
      
      netpilot-meadadigital-com-redirect: 
        rule: Host(`netpilot.meadadigital.com`)
        middlewares: [
          netpilot-meadadigital-com-redirect-https
        ]
        entryPoints: [
          web
        ]
      
      meadadigital-com-redirect: 
        rule: Host(`meadadigital.com`)
        middlewares: [
          meadadigital-com-redirect-https
        ]
        entryPoints: [
          web
        ]
      
      framily-space: 
        rule: Host(`framily.space`)
        service: framily-space-service
        middlewares: []
        priority: 1
        entryPoints: [
          web
        ]
      
    
    services: 
      netpilot-meadadigital-com-api-service: 
        loadBalancer: 
          servers: [
            
              url: http://backend:3001
            
          ]
        
      
      netpilot-meadadigital-com-service: 
        loadBalancer: 
          servers: [
            
              url: http://frontend:3000
            
          ]
        
      
      framily-space-service: 
        loadBalancer: 
          servers: [
            
              url: http://172.18.0.1:9292
            
          ]
        
      
    
    middlewares: 
      websocket-headers:
        headers:
          customRequestHeaders:
            Connection: "upgrade"
            Upgrade: "websocket"
          customResponseHeaders:
            Connection: "upgrade"
            Upgrade: "websocket"
        
      netpilot-meadadigital-com-redirect-https: 
        redirectScheme: 
          scheme: https
          permanent: true
        
      
      meadadigital-com-redirect-https: 
        redirectScheme: 
          scheme: https
          permanent: true
        
      
    
  
