http:
  routers:
    r_meadadigital_com_1_http:
      rule: "Host(`meadadigital.com`) && PathPrefix(`/`) && Method(`GET`)"
      service: noop
      entryPoints:
        - web
      priority: 100
      middlewares:
        - m_https_meadadigital_com_1
    r_meadadigital_com_1:
      rule: "Host(`meadadigital.com`) && PathPrefix(`/`) && Method(`GET`)"
      service: s_meadadigital_com_1
      entryPoints:
        - websecure
      priority: 100
      tls:
        certResolver: letsencrypt
  services:
    noop:
      loadBalancer:
        servers:
          - 
            url: "http://127.0.0.1:1"
    s_meadadigital_com_1:
      loadBalancer:
        servers:
          - 
            url: "http://host.docker.internal:8989"
  middlewares:
    m_https_meadadigital_com_1:
      redirectScheme:
        scheme: https
        permanent: true
