http:
  routers:
    r_test_example_com_2_http:
      rule: "Host(`test.example.com`) && PathPrefix(`/`) && Method(`GET`)"
      service: api@internal
      entryPoints:
        - web
      priority: 100
      middlewares:
        - m_https_test_example_com_2
    r_test_example_com_2:
      rule: "Host(`test.example.com`) && PathPrefix(`/`) && Method(`GET`)"
      service: s_test_example_com_2
      entryPoints:
        - web
      priority: 100
      middlewares:
        - m_https_test_example_com_2
        - m_www_test_example_com_2
  services:
    s_test_example_com_2:
      loadBalancer:
        servers:
          - 
            url: "http://localhost:8989"
  middlewares:
    m_https_test_example_com_2:
      redirectScheme:
        scheme: https
        permanent: true
    m_www_test_example_com_2:
      redirectRegex:
        regex: "^https?://www\.(.*)"
        replacement: "https://${1}"
        permanent: true
