http:
  routers:
    r_test_security_example_com_1_http:
      rule: "Host(`test-security.example.com`) && PathPrefix(`/`)"
      service: api@internal
      entryPoints:
        - web
      priority: 100
      middlewares:
        - m_https_test_security_example_com_1
    r_test_security_example_com_1:
      rule: "Host(`test-security.example.com`) && PathPrefix(`/`)"
      service: s_test_security_example_com_1
      entryPoints:
        - web
      priority: 100
      middlewares:
        - m_https_test_security_example_com_1
        - m_www_test_security_example_com_1
  services:
    s_test_security_example_com_1:
      loadBalancer:
        servers:
          - 
            url: "http://127.0.0.1:3000"
  middlewares:
    m_https_test_security_example_com_1:
      redirectScheme:
        scheme: https
        permanent: true
    m_www_test_security_example_com_1:
      redirectRegex:
        regex: "^https?://www\.(.*)"
        replacement: "https://${1}"
        permanent: true
