http:
  routers:
    r_netpilot_meadadigital_com_3_http:
      rule: "Host(`netpilot.meadadigital.com`) && PathPrefix(`/`) && Method(`GET`)"
      service: api@internal
      entryPoints:
        - web
      priority: 100
      middlewares:
        - m_https_netpilot_meadadigital_com_3
    r_netpilot_meadadigital_com_3:
      rule: "Host(`netpilot.meadadigital.com`) && PathPrefix(`/`) && Method(`GET`)"
      service: s_netpilot_meadadigital_com_3
      entryPoints:
        - websecure
      priority: 100
      middlewares:
        - m_https_netpilot_meadadigital_com_3
        - m_www_netpilot_meadadigital_com_3
      tls:
        certResolver: letsencrypt
  services:
    s_netpilot_meadadigital_com_3:
      loadBalancer:
        servers:
          - 
            url: "http://localhost:8989"
        healthCheck:
          path: /health
          interval: 30s
  middlewares:
    m_https_netpilot_meadadigital_com_3:
      redirectScheme:
        scheme: https
        permanent: true
    m_www_netpilot_meadadigital_com_3:
      redirectRegex:
        regex: "^https?://www\.(.*)"
        replacement: "https://${1}"
        permanent: true
