http:
  routers:
    router-18:
      rule: Host(`framily.space`)
      entryPoints: [web]
      service: service-18
  services:
    service-18:
      loadBalancer:
        servers:
          - url: 'http://laravel.test:80'
